name: release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: web
          ITCH_GAME: we-follow-the-fickle-path
          ITCH_USER: sweetheartsquad
          PACKAGE: dist
          VERSION: ${{ steps.package-version.outputs.current-version }}
      - uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'deployed <https://sweetheartsquad.itch.io/we-follow-the-fickle-path>'
